//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation_SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQ_DEF__AQCALL
    {
        public string QUEUE { get; set; }
        public Nullable<System.Guid> MSG_ID { get; set; }
        public string CORR_ID { get; set; }
        public Nullable<decimal> MSG_PRIORITY { get; set; }
        public string MSG_STATE { get; set; }
        public Nullable<System.DateTime> DELAY { get; set; }
        public Nullable<System.DateTime> DELAY_TIMESTAMP { get; set; }
        public Nullable<decimal> EXPIRATION { get; set; }
        public Nullable<System.DateTime> ENQ_TIME { get; set; }
        public Nullable<System.DateTime> ENQ_TIMESTAMP { get; set; }
        public Nullable<decimal> ENQ_USER_ID { get; set; }
        public string ENQ_TXN_ID { get; set; }
        public Nullable<System.DateTime> DEQ_TIME { get; set; }
        public Nullable<System.DateTime> DEQ_TIMESTAMP { get; set; }
        public Nullable<decimal> DEQ_USER_ID { get; set; }
        public string DEQ_TXN_ID { get; set; }
        public Nullable<decimal> RETRY_COUNT { get; set; }
        public string EXCEPTION_QUEUE_OWNER { get; set; }
        public string EXCEPTION_QUEUE { get; set; }
        public byte[] USER_DATA { get; set; }
        public string ORIGINAL_QUEUE_NAME { get; set; }
        public string ORIGINAL_QUEUE_OWNER { get; set; }
        public string EXPIRATION_REASON { get; set; }
    }
}
