//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation_SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW_WORKLOAD
    {
        public decimal WORKLOADID { get; set; }
        public System.DateTime IMPORT_TIME { get; set; }
        public decimal QUERYID { get; set; }
        public string APPLICATION { get; set; }
        public Nullable<decimal> CARDINALITY { get; set; }
        public Nullable<decimal> RESULTSIZE { get; set; }
        public Nullable<System.DateTime> LASTUSE { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
        public string OWNER { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string QUERY { get; set; }
        public Nullable<decimal> RESPONSETIME { get; set; }
    }
}
