//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation_SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW_FILTERINSTANCE
    {
        public decimal RUNID { get; set; }
        public Nullable<decimal> FILTERID { get; set; }
        public Nullable<decimal> SUBFILTERNUM { get; set; }
        public string SUBFILTERTYPE { get; set; }
        public string STR_VALUE { get; set; }
        public Nullable<decimal> NUM_VALUE1 { get; set; }
        public Nullable<decimal> NUM_VALUE2 { get; set; }
        public Nullable<System.DateTime> DATE_VALUE1 { get; set; }
        public Nullable<System.DateTime> DATE_VALUE2 { get; set; }
    }
}
