//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservation_SYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIEW_RECOMMENDATIONS
    {
        public decimal RUNID { get; set; }
        public string ALL_TABLES { get; set; }
        public string FACT_TABLES { get; set; }
        public string GROUPING_LEVELS { get; set; }
        public string QUERY_TEXT { get; set; }
        public decimal RECOMMENDATION_NUMBER { get; set; }
        public string RECOMMENDED_ACTION { get; set; }
        public string MVIEW_OWNER { get; set; }
        public string MVIEW_NAME { get; set; }
        public Nullable<decimal> STORAGE_IN_BYTES { get; set; }
        public Nullable<decimal> PCT_PERFORMANCE_GAIN { get; set; }
        public decimal BENEFIT_TO_COST_RATIO { get; set; }
    }
}
